-- AlterTable
ALTER TABLE "EmailThread" ADD COLUMN IF NOT EXISTS "toEmails" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "EmailThread" ADD COLUMN IF NOT EXISTS "ccEmails" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "EmailThread" ADD COLUMN IF NOT EXISTS "bccEmails" TEXT NOT NULL DEFAULT '[]';
