import PDFDocument from "pdfkit";
import type { FinancialReportData } from "./financial-report";
import { CRES_DYNAMICS_PDF_COMPANY } from "../../lib/company-pdf";

function money(amount: number, currency: string): string {
  const cur = currency === "KES" ? "KES" : currency || "KES";
  try {
    return new Intl.NumberFormat("en-KE", { style: "currency", currency: cur }).format(amount);
  } catch {
    return `${cur} ${amount.toFixed(2)}`;
  }
}

function fmtDate(iso: string): string {
  return iso.slice(0, 10);
}

function categoryLabel(c: string): string {
  const map: Record<string, string> = {
    salaries: "Salaries (HR / payroll)",
    developer_payment: "Developer payment (project delivery)",
    apis_per_project: "APIs per project"
  };
  return map[c] ?? c.replace(/_/g, " ");
}

/**
 * Branded one-page financial summary PDF for download / admin email.
 */
export async function generateFinancialReportPdf(data: FinancialReportData): Promise<Buffer> {
  const company = CRES_DYNAMICS_PDF_COMPANY;
  const doc = new PDFDocument({ size: "A4", margins: { top: 44, right: 44, bottom: 44, left: 44 } });
  const buffers: Buffer[] = [];
  doc.on("data", (c) => buffers.push(c));

  const pageW = doc.page.width;
  const margin = 44;
  const textW = pageW - margin * 2;

  doc.font("Helvetica-Bold").fontSize(16).fillColor("#0F172A").text(company.name, margin, margin);
  doc.font("Helvetica").fontSize(9).fillColor("#64748B").text(company.website, margin, doc.y + 2);

  doc.moveDown(1.2);
  doc.font("Helvetica-Bold").fontSize(20).fillColor("#059669").text("Financial Report", margin);
  doc.font("Helvetica").fontSize(11).fillColor("#334155").text(data.period.label, margin, doc.y + 4);
  doc
    .fontSize(9)
    .fillColor("#64748B")
    .text(`${fmtDate(data.period.from)} → ${fmtDate(data.period.to)} · Generated ${fmtDate(data.generatedAt)}`, margin);

  doc.moveDown(1);

  const section = (title: string) => {
    doc.moveDown(0.6);
    doc.font("Helvetica-Bold").fontSize(11).fillColor("#0F172A").text(title, margin);
    doc.moveDown(0.25);
  };

  const row = (label: string, value: string, bold = false) => {
    doc.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(10).fillColor("#334155");
    const y = doc.y;
    doc.text(label, margin, y, { width: textW * 0.55, continued: false });
    doc.text(value, margin + textW * 0.55, y, { width: textW * 0.45, align: "right" });
    doc.moveDown(0.15);
  };

  section("Money in — client payments");
  row("Confirmed payments (period)", money(data.revenue.inPeriod, data.currency));
  row("Payment transactions", String(data.revenue.paymentCount));
  row("All-time client revenue", money(data.revenue.allTime, data.currency));

  section("Money out — expenses & payouts");
  row("Expenses (period)", money(data.expenses.inPeriod, data.currency));
  row("Salaries / HR payroll (period)", money(data.salaries.inPeriod, data.currency));
  row("Developer project payments (period)", money(data.developerPayments.inPeriod, data.currency));
  row("Payouts paid (period)", money(data.payouts.paidInPeriod, data.currency));
  row("Total outflows (period)", money(data.cashFlow.totalOutflowsInPeriod, data.currency), true);

  section("Net cash movement");
  row("Net (period)", money(data.cashFlow.netInPeriod, data.currency), true);
  row("Net (all time)", money(data.derived.netCashMovementAllTime, data.currency));

  section("Receivables & projects");
  row("Outstanding / remaining", money(data.invoices.outstandingAmount, data.currency));
  row("Open invoice balance", money(data.invoices.openInvoiceRemaining, data.currency));
  row("Overdue invoices", String(data.invoices.overdueCount));
  row("Approved projects", String(data.projects.approvedCount));
  row("Contract value", money(data.projects.totalContractValue, data.currency));
  row("Collected on projects", money(data.projects.totalReceived, data.currency));

  if (data.expenses.byCategory.length > 0) {
    section("Expense breakdown (period)");
    for (const cat of data.expenses.byCategory.slice(0, 8)) {
      row(categoryLabel(cat.category), money(cat.amount, data.currency));
    }
  }

  section("Pending actions");
  row("Approval queue", String(data.pending.approvalQueue));
  row("Payments pending confirmation", String(data.pending.paymentsPending));
  row("Pending payouts", money(data.payouts.pendingAmount, data.currency));

  doc.moveDown(1);
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#94A3B8")
    .text(
      "Payments = client revenue in. Expenses = HR salaries, developer delivery, tools & ops out. " +
        "Generated by CresOS Finance.",
      margin,
      doc.y,
      { width: textW }
    );

  doc.end();
  await new Promise<void>((resolve, reject) => {
    doc.on("end", () => resolve());
    doc.on("error", reject);
  });
  return Buffer.concat(buffers);
}
